# Tristan Larsin
# 7 - 24 - 17
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

import sys
import os

def init():
    terms = []
    i = 0

    for a in range(2, 101):
        for b in range(2, 101):
            power = a ** b
            print('Val b: ' + str(b))
            if(i < 1):
                terms.append(power)
            if(i >= 1):
                terms.append(power)

            i += 1

    distintList = set(terms)

    print('Number of terms: ' + str(len(distintList)))
init()
